### PR TITLE
Several Minor Bugfixes

### PR DESCRIPTION
**Pull request by cortner**
- #113
- #112
- #109

### CODE REVIEW

**Comment by cortner** [comment]
@mfherbst @rkurchin -- can one of you take a brief look and confirm this is ok to merge?

**Comment by cortner** [comment]
```
julia> O = AtomsBase.element(8)
julia> O.
appearance     atomic_mass    boil           category
color          cpk_hex        density        discovered_by
el_config      melt           molar_heat     name
named_by       number         period         phase
shells         source         spectral_img   summary
symbol         xpos           ypos
```
Not sure where in here I can extract the number of neutrons?

**Comment by cortner** [comment]
@mfherbst @rkurchin -- sorry to ping you again, this PR is just a few lines. I'd be very grateful to get this approved since it blocks ExtXYZ from being updated to AB_0.4

**Comment by rkurchin** [comment]
The specific answer to your chemistry question is that the reported mass is a weighted average over the different naturally-occurring isotopes of an element. For example, here's the table of this information from [Wikipedia for hydrogen](https://en.wikipedia.org/wiki/Isotopes_of_hydrogen):
image
(the reason that the standard atomic weight below the table is not exactly equal to .999855+.000145*2 is, I think, to do with the fact that for historical reasons, these are nondimensionalized against carbon, which is also not _exactly_ 12 because obviously C-14 etc. exist...I don't endorse this system, but it's what we're stuck with)

In any case, I think the rounding operation you add here is fine as a default behavior – obviously, if people care about isotopic detail, they'll probably implement something themselves that explicitly allows that DoF to be set and perhaps draws from a different database that has that information.

Alternatively, if you want it, it looks like @Gregstrq [has actually made basically this thing](https://github.com/Gregstrq/IsotopeTable.jl) that supposedly interoperates with PeriodicTable, though it hasn't been updated in two years so not sure if anything in there is stale...

**Comment by cortner** [comment]
Any other questions or concerns about the PR?

**Comment by cortner** [comment]
thank you.

**Comment by cortner** [comment]
> But we need to do a proper fix later on. Maybe at the MolSSI meeting. 

I definitely agree with this.

**Comment by Gregstrq** [comment]
> Alternatively, if you want it, it looks like @Gregstrq [has actually made basically this thing](https://github.com/Gregstrq/IsotopeTable.jl) that supposedly interoperates with PeriodicTable, though it hasn't been updated in two years so not sure if anything in there is stale...

Hi, everybody. I would say, that new isotopes do not get discovered every day. What I mean is: one would not expect to update the table of isotopes often, unless there are some mistakes in the way the data was compiled together. And if you do find any, please let me know.

**Comment by cortner** [comment]
@Gregstrq  -- would be great to get your input in #115  please.  I think it is not at all clear yet how to manage this well.

**Pull request merged**
